### PR TITLE
Angular 18 update

### PR DESCRIPTION
**Pull request by MoInMaRvZ**
Updated to angular 18

### CODE REVIEW

**Review by halfurness — APPROVED** [review]

**Comment by egorkel-altexsoft** [comment]
Any updates?

**Comment by halfurness** [comment]
For anyone waiting on this, I've just migrated over to using https://material.angular.io/cdk/drag-drop/overview. It's better maintained and this package doesn't look like it gets much attention.

**Comment by guoliang** [comment]
This PR doesn't contains breaking changes to adjust it for Angular 18. So, for anyone waiting for this PR to be merged you can use npm's [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) property to get the current version to install.

```json
"overrides": {
	"ngx-drag-drop": {
		"@angular/common": "18.0.6",
		"@angular/core": "18.0.6"
	}
}
```

**Comment by henkkelder** [comment]
@ChristofFritz 

Could you handle this PR to enable Angular 18?

**Comment by ChristofFritz** [comment]
Sorry for the big delay here. I'm merging it now.

**Pull request merged**
