### PR TITLE
Fixed IE11 issue with placeholder

### PR DESCRIPTION
**Pull request by gpaucot**
Changed .remove() => .parentNode.removeChild() for cross-browser compatibility
Added needed IE polyfills to demo
Adapted the version of flex-layout to build against the latest matched angular version

### CODE REVIEW

**Comment by nischi** [comment]
Any plan to release that in the near future?

**Comment by reppners** [comment]
Will review soon. Currently moving and had no internet until yesterday. Please bear with me until I got the basics set up :)

**Comment by nischi** [comment]
Cool thanks

**Comment by nischi** [comment]
Sorry to push that again, but any plans to do that in near future?

**Pull request merged**
